site_name: Gitsheet (WIP)
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: amber
      accent: orange
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode   
      primary: amber
      accent: orange
extra:
  alternate:
    - name: Français
      link: /fr/
      lang: fr
    - name: English
      link: /en/ 
      lang: en
# Page tree
nav:
  - Home: index.md
  - Getting started:
    - SSH key: ssh_key.md
    - Most used commands: most_used_commands.md
  - Best Practices:
    - Conventions: conventions.md
    - Pre-commit: pre-commit.md
  - IDE embedded:
    - VS Code : vscode.md
  - Common questions:
    - Common questions: common_questions.md
  - Pull requests:
    - Github: Github.md
    - Azure Devops: azure_devops.md
copyright: |
  &copy; 2024 <a href="https://github.com/quentinlegay"  target="_blank" rel="noopener">Quentin LEGAY</a>