site_name: Gitsheet (WIP)
theme:
  name: material
  features:
    # - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: amber
      accent: orange
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode   
      primary: amber
      accent: orange
extra:
  alternate:
    - name: Français
      link: /fr/
      lang: fr
    - name: English
      link: /en/ 
      lang: en

copyright: |
  &copy; 2024 <a href="https://github.com/quentinlegay"  target="_blank" rel="noopener">Quentin LEGAY</a>